@props(['name'])

{{--
    Font Awesome glyphs for the public site, inlined as SVG.

    The guest-facing layout does not load the Font Awesome webfont any more, so
    `<i class="fa-solid fa-…">` draws nothing out here — this component is the
    only way to put an FA glyph on a public page. (The staff consoles still load
    the sheet, so bare `<i>` keeps working in admin and front-desk views.)

    Why: the sheet and its font were the heaviest thing on the booking journey
    by a distance — 90 KB of render-blocking CSS plus a 119 KB webfont that the
    layout also *preloaded*, so it competed with the stylesheet and the three
    text faces for bandwidth on first paint. Checkout drew 24 distinct glyphs
    out of that. Inlined, the same 24 cost a few hundred compressed bytes and no
    request at all. See layouts/public/base for the removal.

    Sizing follows font-size, not a box: `.icon-solid` is `height: 1em`, which is
    what Font Awesome's own SVG mode does. So the `text-[18px]` that used to size
    the glyph still sizes it, and every call site kept its classes verbatim
    through the swap. Width is `auto` on purpose — FA draws every glyph 512 units
    tall but 256–640 wide, and forcing a square box letterboxes the wide ones.

    Paths come from App\Support\AdminIcons, generated by
    scripts/build-icon-registry.mjs; a name resolves either by intent ("bank")
    or by its Font Awesome name ("building-columns"). Add a glyph by editing
    MAP in that script and running `npm run icons:build` — never by hand.

    Usage: <x-booking.ui.icon-solid name="receipt" class="text-[19px]" />
--}}

@php
    [$viewBox, $path] = \App\Support\AdminIcons::get($name);
@endphp

<svg {{ $attributes->merge(['class' => 'icon-solid']) }} viewBox="{{ $viewBox }}" fill="currentColor"
     aria-hidden="true" focusable="false"><path d="{{ $path }}"/></svg>
