<?php

namespace App\Support;

use Illuminate\Support\Facades\Cache;

/**
 * Looks up the derivatives generated by scripts/build-images.mjs.
 *
 * The manifest is written at build time and read here, so nothing resizes an
 * image during a request. A missing entry is not an error: callers fall back
 * to the original asset, which means <x-img> can be adopted one view at a time
 * and a new photo that has not been through the builder still renders.
 */
class ResponsiveImage
{
    /** Cached for the process; the manifest cannot change mid-request. */
    private static ?array $manifest = null;

    /**
     * Every derivative for one source path, keyed by format.
     *
     * @return array{width:int,height:int,fallback:string,sources:array<string,list<array{w:int,src:string}>>}|null
     */
    public static function lookup(string $path): ?array
    {
        return self::manifest()[ltrim($path, '/')] ?? null;
    }

    /**
     * `image/derived/x-800.webp 800w, image/derived/x-1600.webp 1600w`
     */
    public static function srcset(array $entry, string $format): string
    {
        return collect($entry['sources'][$format] ?? [])
            ->map(fn (array $v) => asset($v['src']).' '.$v['w'].'w')
            ->implode(', ');
    }

    /**
     * The widest fallback derivative — what a browser without srcset support,
     * or an email client, will load.
     */
    public static function fallbackSrc(array $entry): ?string
    {
        $list = $entry['sources'][$entry['fallback']] ?? [];

        return $list ? asset(end($list)['src']) : null;
    }

    private static function manifest(): array
    {
        if (self::$manifest !== null) {
            return self::$manifest;
        }

        $load = function (): array {
            $file = public_path('image/derived/manifest.json');

            if (! is_file($file)) {
                return [];
            }

            return json_decode(file_get_contents($file), true) ?: [];
        };

        // Cached in production so the file is not re-read and re-decoded on
        // every request; read straight through locally so a rebuild shows up
        // without clearing anything.
        self::$manifest = app()->isProduction()
            ? Cache::rememberForever('responsive-images.manifest', $load)
            : $load();

        return self::$manifest;
    }
}
